### PR TITLE
Adds a signal handler for SIGCHLD to clean up zombie processes

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/script_exporter/7)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/script_exporter/7)* status: 0 of 1 LGTMs obtained

___
*[script_exporter.go, line 189 at r1](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYBV7oV0gQQNBHqVzJn:-MYBV7oV0gQQNBHqVzJo:b-venbkw) ([raw file](https://github.com/m-lab/script_exporter/blob/14cf5a5b72e8a8da1ce6c883bca79b9b015aaee1/script_exporter.go#L189)):*
> ```Go
> 	// that never get reaped. When the child does exit, and its parent parent
> 	// process no longer exists, the OS will assign it to the next process up
> 	// the line and send that process as SIGCHLD signal. The below goroutine
> ```

s/as/a/
___
*[script_exporter.go, line 194 at r1](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYBWXTn5ATAKOrYtWgG:-MYBWXTn5ATAKOrYtWgH:b-zcd2z5) ([raw file](https://github.com/m-lab/script_exporter/blob/14cf5a5b72e8a8da1ce6c883bca79b9b015aaee1/script_exporter.go#L194)):*
> ```Go
> 	sigc := make(chan os.Signal, 1)
> 	signal.Notify(sigc, syscall.SIGCHLD)
> 	go func() {
> ```

If this were a helper function, it would be possible to write simple synthetic unit tests for the input events.
___
*[script_exporter.go, line 207 at r1](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYBVJ2q2irkMefeOrLN:-MYBVJ2q2irkMefeOrLO:b74evg7) ([raw file](https://github.com/m-lab/script_exporter/blob/14cf5a5b72e8a8da1ce6c883bca79b9b015aaee1/script_exporter.go#L207)):*
> ```Go
> 				}
> 				log.Infof("Reaped child process: pid=%d, wstatus=%+v\n", pid, wstatus)
> 			default:
> ```

This looks like a busy loop. What's the CPU usage when this runs?

I suggest removing the default case and allowing the select statement to block on `sigc`.

If you wanted to be able to shutdown this goroutine safely, an additional parameter for a context could allow the select to additionally listen for `<-ctx.Done()`.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I believe I have addressed your concerns. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/script_exporter/7#-:-MYGOEfDBybwrPl1ceSq:baey5um)* status: 0 of 1 LGTMs obtained

___
*[script_exporter.go, line 189 at r1](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYBV7oV0gQQNBHqVzJn:-MYBbuEiBMazKc9-uOye:bb6un1j) ([raw file](https://github.com/m-lab/script_exporter/blob/14cf5a5b72e8a8da1ce6c883bca79b9b015aaee1/script_exporter.go#L189)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/as/a/
</blockquote></details>

Done
___
*[script_exporter.go, line 194 at r1](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYBWXTn5ATAKOrYtWgG:-MYGO6lM1PjyisrDbm7h:b-a0jip3) ([raw file](https://github.com/m-lab/script_exporter/blob/14cf5a5b72e8a8da1ce6c883bca79b9b015aaee1/script_exporter.go#L194)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If this were a helper function, it would be possible to write simple synthetic unit tests for the input events.
</blockquote></details>

I have moved this to a helper function now.
___
*[script_exporter.go, line 207 at r1](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYBVJ2q2irkMefeOrLN:-MYGO9Cf3PgqRaJ8OrZt:b3f0mb0) ([raw file](https://github.com/m-lab/script_exporter/blob/14cf5a5b72e8a8da1ce6c883bca79b9b015aaee1/script_exporter.go#L207)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This looks like a busy loop. What's the CPU usage when this runs?

I suggest removing the default case and allowing the select statement to block on `sigc`.

If you wanted to be able to shutdown this goroutine safely, an additional parameter for a context could allow the select to additionally listen for `<-ctx.Done()`.
</blockquote></details>

Done, I believe.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/script_exporter/7)* status: 0 of 1 LGTMs obtained

___
*[script_exporter.go, line 215 at r2](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYGgwfp871ENMvAq4dn:-MYGgwfp871ENMvAq4do:b3vfrwo) ([raw file](https://github.com/m-lab/script_exporter/blob/9b635628b0e2454848e3f585747ec16c71825bc9/script_exporter.go#L215)):*
> ```Go
> 
> 	// Clean up zombie child processes
> 	sigc := make(chan os.Signal, 1)
> ```

Because our deployment of script exporter may have dozens or hundreds of processes, and `signal.Notify` does not guarantee delivery of signals when the channel is full, I suggest that we increase the buffer value proportionately, e.g. 100, maybe even much more.
___
*[script_exporter_test.go, line 30 at r2](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYGgH9X4Yl77xRpGhoD:-MYGgH9Y4zBRjiPSw1Hs:b-a9dc86) ([raw file](https://github.com/m-lab/script_exporter/blob/9b635628b0e2454848e3f585747ec16c71825bc9/script_exporter_test.go#L30)):*
> ```Go
> }
> 
> func TestReapChildren(t *testing.T) {
> ```

The implementation should be POSIX os agnostic.

This unit test is linux specific.

Please move this unit tests to a new file (e.g. script_exporter_linux_test.go) with the build tag for linux `// +build linux`
___
*[script_exporter_test.go, line 58 at r2](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYGi9oC5FCdG4WWfcpm:-MYGi9oC5FCdG4WWfcpn:b-2ulwez) ([raw file](https://github.com/m-lab/script_exporter/blob/9b635628b0e2454848e3f585747ec16c71825bc9/script_exporter_test.go#L58)):*
> ```Go
> 
> 	// Cancel the context
> 	mainCancel()
> ```

Please verify that the go routine returns. You can do this with something like:

```
done := make(chan bool)
go func() {
    reapChildren(mainCtx, sigc)
    close(done)
}()

...

mainCancel()
<-done
```

If the function under test failed to return the unit test would hang. If you wanted to ensure that it returned but failed, you could additionally select on the `done` channel and a timer.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/script_exporter/7#-:-MYH88_m2Erb6qBTWK-A:b-e77fnf)* status: 0 of 1 LGTMs obtained

___
*[script_exporter.go, line 215 at r2](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYGgwfp871ENMvAq4dn:-MYGyH7Y7-Kr9e4aqdED:bdgegor) ([raw file](https://github.com/m-lab/script_exporter/blob/9b635628b0e2454848e3f585747ec16c71825bc9/script_exporter.go#L215)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Because our deployment of script exporter may have dozens or hundreds of processes, and `signal.Notify` does not guarantee delivery of signals when the channel is full, I suggest that we increase the buffer value proportionately, e.g. 100, maybe even much more.
</blockquote></details>

I set it to 500, which is, at the moment, just slightly more than the count of production nodes.
___
*[script_exporter_test.go, line 30 at r2](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYGgH9X4Yl77xRpGhoD:-MYH0XhuA6WLnDzNjgov:b-896fix) ([raw file](https://github.com/m-lab/script_exporter/blob/9b635628b0e2454848e3f585747ec16c71825bc9/script_exporter_test.go#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The implementation should be POSIX os agnostic.

This unit test is linux specific.

Please move this unit tests to a new file (e.g. script_exporter_linux_test.go) with the build tag for linux `// +build linux`
</blockquote></details>

Done.
___
*[script_exporter_test.go, line 58 at r2](https://reviewable.io/reviews/m-lab/script_exporter/7#-MYGi9oC5FCdG4WWfcpm:-MYH1-iLAPuDJ3rMDaZy:b64ts8) ([raw file](https://github.com/m-lab/script_exporter/blob/9b635628b0e2454848e3f585747ec16c71825bc9/script_exporter_test.go#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please verify that the go routine returns. You can do this with something like:

```
done := make(chan bool)
go func() {
    reapChildren(mainCtx, sigc)
    close(done)
}()

...

mainCancel()
<-done
```

If the function under test failed to return the unit test would hang. If you wanted to ensure that it returned but failed, you could additionally select on the `done` channel and a timer.
</blockquote></details>

Done, minus checking a return with failure.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/script_exporter/7#-:-MYH9Qc63fR_9IYQ7lLi:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
