### PR TITLE
Adds a third metric named 'script_exit_code' 

### PR DESCRIPTION
**Pull request by nkinkade**
This new metric will contain the return code of the script run.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/script_exporter/2)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Nice! :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[script_exporter.go, line 71 at r1](https://reviewable.io:443/reviews/nkinkade/script_exporter/2#-L4by_mPxEipbk4iKXgk:-L4by_mPxEipbk4iKXgl:b-a3cuqt) ([raw file](https://github.com/nkinkade/script_exporter/blob/7009df45b525cc2a8afb506fd24c4a54faf2a1fb/script_exporter.go#L71)):*
> ```Go
> 	if err = cmd.Run(); err != nil {
> 		log.Infof("Command failed with error: %v", err)
> 		if exitError, ok := err.(*exec.ExitError); ok {
> ```

If this check does not pass, then rc will never be assigned, so still have the default value, 0. Is this intended?

---

*[script_exporter.go, line 75 at r1](https://reviewable.io:443/reviews/nkinkade/script_exporter/2#-L4bykaZbAk62aXZb-py:-L4bykaZbAk62aXZb-pz:b-mekcgf) ([raw file](https://github.com/nkinkade/script_exporter/blob/7009df45b525cc2a8afb506fd24c4a54faf2a1fb/script_exporter.go#L75)):*
> ```Go
> 		}
> 	} else {
> 		log.Infof("Command succeeded with error: %v", err)
> ```

err will be nil in this case, so no need to print it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nkinkade/script_exporter/2#-:-L4bzz4NNHosEsA9hO8U:be8rotp)*

**Comment by nkinkade** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[script_exporter.go, line 71 at r1](https://reviewable.io:443/reviews/m-lab/script_exporter/2#-L4by_mPxEipbk4iKXgk:-L4c1QsZgxZG-D7IsET-:bw7clnd) ([raw file](https://github.com/m-lab/script_exporter/blob/7009df45b525cc2a8afb506fd24c4a54faf2a1fb/script_exporter.go#L71)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If this check does not pass, then rc will never be assigned, so still have the default value, 0. Is this intended?
</blockquote></details>

I removed the `if` wrapper because it's not clear to me how/why that command would ever fail. Does this seem reasonable?

---

*[script_exporter.go, line 75 at r1](https://reviewable.io:443/reviews/m-lab/script_exporter/2#-L4bykaZbAk62aXZb-py:-L4c0C_1fpJBDFDrCKwD:bbf5luk) ([raw file](https://github.com/m-lab/script_exporter/blob/7009df45b525cc2a8afb506fd24c4a54faf2a1fb/script_exporter.go#L75)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

err will be nil in this case, so no need to print it.
</blockquote></details>

Oh, shoot. That was for debugging, and I just forgot to remove it! Removed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/script_exporter/2)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[script_exporter.go, line 71 at r1](https://reviewable.io:443/reviews/m-lab/script_exporter/2#-L4by_mPxEipbk4iKXgk:-L4c2MiFtWXP57nmKjUJ:b-9r5n3n) ([raw file](https://github.com/m-lab/script_exporter/blob/7009df45b525cc2a8afb506fd24c4a54faf2a1fb/script_exporter.go#L71)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I removed the `if` wrapper because it's not clear to me how/why that command would ever fail. Does this seem reasonable?
</blockquote></details>

This lgtm -- the error value returned by cmd.Run is documented as being an instance of *exec.ExitError, so this should be safe.

You can express it simply as:
```
exitError := err.(*exec.ExitError)
```

Dropping the unused value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/script_exporter/2)*

**Comment by nkinkade** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[script_exporter.go, line 71 at r1](https://reviewable.io:443/reviews/m-lab/script_exporter/2#-L4by_mPxEipbk4iKXgk:-L4c4beJxSlAPxbCr0Qc:b-oe7vqb) ([raw file](https://github.com/m-lab/script_exporter/blob/7009df45b525cc2a8afb506fd24c4a54faf2a1fb/script_exporter.go#L71)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This lgtm -- the error value returned by cmd.Run is documented as being an instance of *exec.ExitError, so this should be safe.

You can express it simply as:
```
exitError := err.(*exec.ExitError)
```

Dropping the unused value.
</blockquote></details>

Thanks for tip. I removed the unused value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/script_exporter/2)*

**Pull request merged**
